# Default configuration for Mirror Descent experiments
# This file contains the default hyperparameters and settings

# Data configuration
data:
  name: "synthetic"
  input_dim: 100
  n_samples: 1000
  noise_level: 0.1
  separation: 1.0
  test_ratio: 0.2
  seed: 42

# Model configuration
model:
  type: "DeepLinear"
  input_dim: 100
  output_dim: 1
  hidden_dims: [50, 25]
  bias: true

# Optimizer configuration
optimizer:
  type: "MirrorDescent"
  potential: "quadratic"
  learning_rate: 0.01
  momentum: 0.0
  weight_decay: 0.0

# Training configuration
training:
  epochs: 1000
  batch_size: 32
  early_stopping:
    patience: 50
    min_delta: 1e-6
  save_frequency: 100

# Evaluation configuration
evaluation:
  metrics: ["margin", "alignment", "angles", "spectral"]
  baseline_methods: ["svm", "logistic_regression", "ridge_regression"]

# Logging configuration
logging:
  level: "INFO"
  log_dir: "logs"
  save_models: true
  plot_frequency: 50
