# MNIST binary classification experiments
# Systematic exploration of digit pairs, PCA dimensions, and potential functions

dataset: mnist
epochs: 50  # Fewer epochs for MNIST
lr: 0.02   # Lower learning rate for MNIST
log_frequency: 5

# Grid parameters
potentials: [quadratic, lp]  # Focus on key potentials for MNIST
p_values: [1.5, 3.0]  # Only used for lp potential
depths: [1, 2]
seeds: [0, 1, 2]

# MNIST-specific parameters
digits_combinations: [[0, 1], [3, 5]]  # Two digit pairs for comparison
pca_components: [50, 200]  # Two PCA dimensions

# Notes:
# - This will create 2 * 2 * 2 * 3 * 2 * 2 = 96 experiments total
# - Tests different digit pairs: 0 vs 1 and 3 vs 5
# - Two PCA dimensions: 50 and 200 components
# - Focuses on quadratic and Lp potentials with p=1.5 and p=3.0
# - Expected runtime: 1-2 hours depending on hardware
# - Produces MNIST-specific results for real-world validation
