# Grid configuration for MNIST experiments
# This file specifies parameter combinations for MNIST binary classification

dataset: mnist
epochs: 50  # Fewer epochs for MNIST
lr: 0.02   # Lower learning rate for MNIST
log_frequency: 5

# Grid parameters
potentials: [quadratic, lp, layer_scaled]
p_values: [1.5, 2.0, 3.0]  # Only used for lp potential
depths: [1, 2, 3]
seeds: [0, 1, 2]

# MNIST-specific parameters
digits_combinations: [[0, 1], [3, 5], [7, 9]]  # Different digit pairs
pca_components: [50, 100, null]  # Different PCA dimensions (null = no PCA)

# Notes:
# - This will create 3 * 3 * 3 * 3 * 3 * 3 = 729 experiments total
# - Each combination tests different digit pairs and PCA dimensions
# - Results will show how potential functions affect MNIST classification
